#!/bin/sh

rm -R /home/lost+found

#echo "busca usuarios, cria script copia de diretorio"
ls /home/ | awk '{print "cp -Rf /etc/skel/.gimp-2.8 /home/" $1 "/"}' | cat >/tmp/usersphotogimp.sh
#echo "busca usuarios, cria script altera permissoes"
ls /home/ | awk '{print "chown -R " $1 ":" $1 " /home/"$1"/.gimp-2.8"}' | cat >>/tmp/usersphotogimp.sh

#echo "permissoes no dir para novos users"
chmod -R 755 /etc/skel/.gimp-2.8

#echo "permissoes para execucao do script criado no dir tmp"
chmod 777 /tmp/usersphotogimp.sh

/tmp/usersphotogimp.sh

echo "## Operação concluida ##"
echo "Acesse: http://duzeru.org"
echo "Acesse: diolinux.com.br"

